repos:
  - repo: local
    hooks:
      - id: gofmt
        name: go fmt
        entry: gofmt -w
        language: system
        types: [go]
      - id: staticcheck
        name: staticcheck
        entry: staticcheck
        language: golang
        pass_filenames: false
        args: [./...]
        additional_dependencies:
          - honnef.co/go/tools/cmd/staticcheck@latest
      - id: govet
        name: go vet
        entry: go vet ./...
        language: system
        pass_filenames: false
